/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.darkprograms.modelbot.gui;

import com.darkprograms.modelbot.util.LanguageDetectUtil;
import com.darkprograms.modelbot.util.MainUtil;
import com.darkprograms.modelbot.util.RefreshAccessTokenTask;
import com.darkprograms.modelbot.util.TweetThread;

import java.awt.*;

/**
 * @author theshadow
 */
public class MainGUI extends javax.swing.JFrame implements TweetThread.OnTweetListener, RefreshAccessTokenTask.OnRefreshListener {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        english = new javax.swing.JCheckBox();
        retweet = new javax.swing.JCheckBox();
        connectTwitter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        startBot = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ModelBot");

        jLabel1.setText("Model Bot v1.50");

        jLabel2.setText("By Luke Kuza");

        english.setText("Only Retweet English?");

        retweet.setText("Use format: \"RT @example tweet\"");

        connectTwitter.setText("Connect To Twitter");
        connectTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectTwitterActionPerformed(evt);
            }
        });

        jLabel3.setText("Text to Search For:");

        jLabel4.setText("Logs:");

        log.setEditable(false);
        log.setColumns(20);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        startBot.setText("Start Bot");
        startBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBotActionPerformed(evt);
            }
        });

        jLabel5.setText("Status:");

        status.setText("Waiting...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(connectTwitter)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(english)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(retweet, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(searchText))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(startBot)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)
                                .addComponent(connectTwitter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(english)
                                        .addComponent(retweet))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startBot)
                                        .addComponent(jLabel5)
                                        .addComponent(status))
                                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void startBotActionPerformed(java.awt.event.ActionEvent evt) {

        if (!MainUtil.getInstance().isRunning()) {
            MainUtil.getInstance().setEnglish(english.isSelected());
            MainUtil.getInstance().setRetweetQuote(retweet.isSelected());
            MainUtil.getInstance().setSearchString(searchText.getText());
            MainUtil.getInstance().setRunning(true);
            startBot.setText("Stop Bot");
            status.setText("Started");
            MainUtil.getInstance().setTweetThread(new Thread(new TweetThread(this)));
            MainUtil.getInstance().getTweetThread().start();
        } else {
            MainUtil.getInstance().setRunning(false);
            MainUtil.getInstance().getTweetThread().interrupt();
            startBot.setText("Start Bot");
            status.setText("Stopped");
        }
    }

    private void connectTwitterActionPerformed(java.awt.event.ActionEvent evt) {
        if (Desktop.isDesktopSupported()) {
            MainUtil.getInstance().connectToTwitter(true);
        } else {
            MainUtil.getInstance().connectToTwitter(false);
        }
    }

    @Override
    public void onTweet(String response) {
        log.append(response + "\n");
    }


    @Override
    public void onRefresh(String response) {
        log.append(response + "\n");
    }


    // Variables declaration - do not modify
    private javax.swing.JButton connectTwitter;
    private javax.swing.JCheckBox english;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea log;
    private javax.swing.JCheckBox retweet;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton startBot;
    private javax.swing.JLabel status;
    // End of variables declaration

}
